### PR TITLE
Address book reworks + misc fixes

### LINKED ISSUE #85: address book has issues
* cant bulk remove, have to click on each thing
* no scroll bar (!!)
* seems to be a lag when i click and when it shows the details

also maybe change ur address entry to use an integrated address instead

### LINKED ISSUE #92: Tries to open wallet and errors when node list updating
img

Make it so that it doesn't attempt to open the wallet - and thus not display that ugly red message - till the node list is updated and something is chosen

### PR DESCRIPTION
**Pull request by rixombea**
- Allow to create a new, password protected address book file. Builtin/shared address book still available and used by default.
- Resolved #85: bulk delete + list performance & ui tweaks
- Prevent opening wallet while remote node list being updated (fixes #92)

### CODE REVIEW

**Comment by Sajo8** [comment]
* Changing address books takes 420 years
* Setting a password for a new address book shouldn't be mandatory

**Comment by Sajo8** [comment]
* Grey out the "send trtl button". If attempted to click on, show the "workin on it" thing

**Comment by Sajo8** [comment]
* Show password button when unlocking an address book doesn't work

**Comment by Sajo8** [comment]
* Useless side scroll bar https://i.imgur.com/egfmYEe.gifv

**Comment by Sajo8** [comment]
"Delete" button persists when I click "add a new entry" thing while some stuff are selected. https://i.imgur.com/9WtaxkZ.gifv

**Comment by Sajo8** [comment]
* "x entries ~~has~~ have been deleted" change that string

**Comment by Sajo8** [comment]
* "1 ~~entries~~ entry has been deleted" if it's one set it to be entry

**Comment by Sajo8** [comment]
Node list is severely impacted for some reason
* every node is listed as a custom node
* cant see fee
* cant see bottom of list when in windowed mode, should detect dimensions and cut off

https://i.imgur.com/jfrDgG8.png
https://i.imgur.com/8XbZJe9.png

**Comment by rixombea** [comment]
> Node list is severely impacted for some reason
> 
> * every node is listed as a custom node
> * cant see fee

This issue happens when connection borked or no internet connection during updating node list, it will be switched to fallback mode, where all untested nodes (from json repo) will be listed w/o fee info, but are currently mislabeled as "Custom Node" -- fixes is on the way.

**Comment by rixombea** [comment]
> * Grey out the "send trtl button". If attempted to click on, show the "workin on it" thing

new "send trtl" feature already implemented in last commit, no need for 'under development' message anymore

> * Show password button when unlocking an address book doesn't work

fixed.

>* "Delete" button persists when I click "add a new entry" thing while some stuff are selected.
> * "x entries has have been deleted" change that string
> * Useless side scroll bar https://i.imgur.com/egfmYEe.gifv
> * "1 entries entry has been deleted" if it's one set it to be entry

fixed, fixed, fixed & fixed.

> * Setting a password for a new address book shouldn't be mandatory

No, this new feature was added as requested by some users who concern with their address book privacy, if you're fine with shared/passwordless address book, use default/built-in one.

> Node list is severely impacted for some reason
> * every node is listed as a custom node
> * cant see fee
> * cant see bottom of list when in windowed mode, should detect dimensions and cut off

This one should be in different issue, but last commit also fixes this

**Comment by rixombea** [comment]
:point_up:

**Comment by Sajo8** [comment]
> No, this new feature was added as requested by some users who concern with their address book privacy, if you're fine with shared/passwordless address book, use default/built-in one.
It shouldn't matter, if someone wants multiple address books then let them ahve them without having to make a password. Sometimes we want to organise them w/out having to deal with a password because most likely they'll either complain, or set a stupid password making it irrelevant anyways. If those people are concerned about their privacy, then they can add their own password. Let it be ***optional***

**Comment by Sajo8** [comment]
> 
> 
> point_up

lol thanks

**Comment by Sajo8** [comment]
@rixombea link expired, can I get another?

**Comment by zpalmtree** [comment]
bruh who sends to so many people they need multiple address books

1) tipjar
2) exchange
3) your drug dealer
4) your mate

who tf else are you sending to

**Comment by Sajo8** [comment]
Also @rixombea when entering the password for an address book (which shouldnt be necessary ;) ) i have to click open instead of being able to press enter, can you let us press enter instead of having to click open?

**Comment by Sajo8** [comment]
also: "back" button in address back takes it back to home page, regardless of what page we actually switched from

**Comment by rixombea** [comment]
> Also @rixombea when entering the password for an address book (which shouldnt be necessary ;) ) i have to click open instead of being able to press enter, can you let us press enter instead of having to click open?

submit with enter: fixed.
As for password requirement on extra address book, I'll leave it as is for now, and wait for feedbacks from other users.

> also: "back" button in address back takes it back to home page, regardless of what page we actually switched from

Only from main/non-contextual screens, call it "Back Home" if you wish :smile:

**Pull request merged**
